### ISSUE TITLE
Possible abstraction?

### ISSUE THREAD

**Issue by KrystilizeNevaDies** [jaskarth/overworld-two#10]
Heya, I'm a contributor to [Minestom](https://github.com/Minestom/Minestom),

Was just wondering if there are any plans to make the code base more abstract for multi-platform use?

And if not, is there interest in making plans?

Minestom lacks a good vanilla-like generator at the moment, overworld-two would be a perfect match.
Thanks

**Comment by Gegy** [comment]
Overworld Two is unfortunately largely based on rewriting small parts of the generator, while maintaining most of it. Unfortunately it is not enough of a reimplementation that I don't think it could be of so much use :(

**Comment by KrystilizeNevaDies** [comment]
Okay, thanks for the info!

It's unfortunate that it wouldn't work out that well :(
