### ISSUE TITLE
Loading screen freezes at 0% with Phosphor

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [jaskarth/overworld-two#18]
When using the 'new-perlin-noise' branch (cannot be reproduced with the main 1.16.2 branch), Fabric API (dependency of Overworld Two) and either [Phosphor Fabric v0.7.1](https://github.com/CaffeineMC/phosphor-fabric/releases/tag/mc1.16.2-v0.7.1) or [MC-Lighting-Fixes](https://github.com/PhiPro95/mc-fixes/releases/tag/lighting-fixes-v1.0.0), then the loading screen freezes at 0% and there is a log spam.

System/Minecraft:
- Minecraft 1.16.5
- Fabric Loader 0.11.3
- MultiMC 5 (0.6.12)
- Fabric API 0.32.5
- Windows 10
- AdoptOpenJDK 16 (OpenJ9)

Minecraft logs:
- With Phosphor: https://gist.github.com/DragonEggBedrockBreaking/94f2f55f3cc57a7e8b45d55e2cf61a5e
- With MC-Lighting-Fixes: https://gist.github.com/DragonEggBedrockBreaking/f71d798a35121e0e83dbc2babe2484cc

**Comment by Sirbucket** [comment]
Code conflict in the ProtoChunk mixin.
